---
title: "ccbr1040_mRNA"
author: "Da"
date: "5/31/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#suppressMessages(require(SingleCellExperiment))
library(Seurat)
library(dplyr)
library(ggplot2)
library(reshape2)
library(RColorBrewer)
library(ComplexHeatmap)
library(tidyverse)
library(Matrix)
library(SingleR)
library(cowplot)
library(SingleR)
library(Routliers)
#library("URD")
#library("DoubletFinder")
#library(scRNAseq)
library(here)
library(harmony)
library(batchelor)
library(devtools)
library(SeuratWrappers)
theme_set(theme_classic())
```


```{r}
setwd("~/Desktop/active_projects/ccbr1040_scTCRseq/analysis/")
so = readRDS("~/Desktop/active_projects/seuratObject/ccbr1040_noDoublet_soReshape.5.31.2020.rds")

so@meta.data$group = ifelse(so@meta.data$sample_name=="1MF1", "het",
                               ifelse(so@meta.data$sample_name=="3MF1", "het",
                                      ifelse(so@meta.data$sample_name=="1MF2", "ko", "ko")))

so@meta.data$batch %>% table()

```


```{r}
Idents(so) = "new_name"
so_ave = AverageExpression(object = so, assays = "SCT")
DefaultAssay(so)
```


```{r}
genes_of_interest = read.csv("results/processedData/genes_of_interest.csv", header = T, stringsAsFactors = F)


mySeuratPlot = function(genes){
  
  DefaultAssay(so) = "RNA"

  name = deparse(substitute(genes))
  p1 = VlnPlot(so, features = genes, pt.size = 0.001)+NoLegend()
  pdf(paste0("VlnPlot_", name, ".pdf"), width = 18, height = 14)
  print(p1)
  dev.off()
  
  p2 = FeaturePlot(so, features = genes, reduction = "tsne", split.by = "group")
  pdf(paste0("FeaturePlot_", name, ".pdf"), width = 12, height = ifelse(2<length(genes)&length(genes)<=3, 10,
                                                                        ifelse(4<=length(genes)&length(genes)<=5, 13,
                                                                               ifelse(6<=length(genes)&length(genes)<=8, 20, 
                                                                                      ifelse(length(genes)==2, 6, 26)))))
  print(p2)
  dev.off()
  
  p3 = DotPlot(so, features = genes) + RotatedAxis()
  pdf(paste0("DotPlot_", name, ".pdf"), width = 9, height = 9)
  print(p3)
  dev.off()
  
  mat = so_ave$integrated[which(rownames(so_ave$integrated)%in%genes),]
  
  # p4 = 
  # ComplexHeatmap::Heatmap(matrix = t(scale(t(data.matrix(mat)))), name="Z-score", km=1, 
  #                       col=colorRampPalette(c("darkblue","grey","darkred"))(256), 
  #                       row_names_gp = gpar(fontsize = ifelse(nrow(mat) <= 30, 10, 
  #                                                      ifelse(30<nrow(mat)&nrow(mat) <= 45, 7,
  #                                                      ifelse(45<nrow(mat)&nrow(mat) <= 60, 5, 4))), 
  #                                           fontface = "bold"),
  #                       column_names_gp = gpar(fontsize = 10, fontface = "bold"),
  #                       cluster_columns = T ,column_title_gp = gpar(fontsize = 10, fontface = "bold"), 
  #                       column_names_rot = 65, width = unit(8, "cm"),
  #                       column_title = name)
  # 
  # pdf(paste0("Heatmap_", name, ".pdf"), width = 10, height = 10)
  # print(p4)
  # dev.off()
  
  p5 = RidgePlot(so, features = genes)+NoLegend()
  pdf(paste0("RidgePlot_", name, ".pdf"), width = 18, height = 14)
  print(p5)
  dev.off()  
  
  p6 = DoHeatmap(object = so, features = genes)
  pdf(paste0("DoHeatmap_", name, ".pdf"))
  print(p6)
  dev.off() 
}
library(RColorBrewer)

myFeaturePlot = function(genes, w, h){
  name = deparse(substitute(genes))
  p2 = FeaturePlot(so, features = genes, reduction = "tsne", split.by = "group",cols = c("lightgrey","red"), order = TRUE)
  pdf(paste0("FeaturePlot_", name, ".pdf"), width = w, height = h)
  print(p2)
  dev.off()
}

myFeaturePlot(genes = TCR_components, 12,15)

myFeaturePlot(genes = CoReceptors_CoSignalingMolecules,12,20)

myFeaturePlot(genes = cytokineReceptors_chemokineReceptors,12,18)
myFeaturePlot(genes = adhesionMolecules_guidanceMolecules,12,23)
myFeaturePlot(genes = otherSurfaceMolecules,10,6)
myFeaturePlot(genes = signalMolecules,12,31)
myFeaturePlot(genes = transcriptionFactors,12,33)
myFeaturePlot(genes = otherMolecules,12,30)


TCR_components = genes_of_interest[which(genes_of_interest$type=="TCR_components"), c("gene")]
CoReceptors_CoSignalingMolecules = genes_of_interest[which(genes_of_interest$type=="CoReceptors_CoSignalingMolecules"), c("gene")]
cytokineReceptors_chemokineReceptors = genes_of_interest[which(genes_of_interest$type=="cytokineReceptors_chemokineReceptors"), c("gene")]
adhesionMolecules_guidanceMolecules = genes_of_interest[which(genes_of_interest$type=="adhesionMolecules_guidanceMolecules"), c("gene")]
otherSurfaceMolecules = genes_of_interest[which(genes_of_interest$type=="otherSurfaceMolecules"), c("gene")]
signalMolecules = genes_of_interest[which(genes_of_interest$type=="signalMolecules"), c("gene")]
transcriptionFactors = genes_of_interest[which(genes_of_interest$type=="transcriptionFactors"), c("gene")]
otherMolecules = genes_of_interest[which(genes_of_interest$type=="otherMolecules"), c("gene")]

```

```{r}
mySeuratPlot(genes = TCR_components)

mySeuratPlot(genes = CoReceptors_CoSignalingMolecules)

mySeuratPlot(genes = cytokineReceptors_chemokineReceptors)
mySeuratPlot(genes = adhesionMolecules_guidanceMolecules)
mySeuratPlot(genes = otherSurfaceMolecules)
mySeuratPlot(genes = signalMolecules)
mySeuratPlot(genes = transcriptionFactors)
mySeuratPlot(genes = otherMolecules)

annotations = c("tsne", "umap")
for (i in annotations){
  p = DimPlot(so, reduction = i, group.by = "hash.ID")
  pdf(paste0("DimPlot_",i,".pdf"))
  print(p)
  dev.off()
}

p1= 
DimPlot(so, reduction = "tsne", group.by = "hash.ID")


DimPlot(so, reduction = "umap", group.by = "hash.ID")


```

```{r}
a <- DotPlot(object = so, features = c("Cxcr4"))
a$data



so@assays$RNA@data[c("Cxcr4"),] %>% plot()

so@assays$RNA@counts[c("Plxnd1"),] %>% plot()

expr.pct = function(geneName){
  df = so@assays$RNA@counts[c(geneName),] %>% table() %>% data.frame() 
  df$fraction = df$Freq/sum(df$Freq)
  colnames(df)[1] = "Count"
  df$gene = geneName
  return(df)
}

Bcl2 = expr.pct("Bcl2")
Plxnd1 = expr.pct("Plxnd1")
Cxcr4 = expr.pct("Cxcr4")
S1pr1 = expr.pct("S1pr1")
Ccr7 = expr.pct("Ccr7")
Ccr9 = expr.pct("Ccr9")
Itgb2 = expr.pct("Itgb2")
Itgb7 = expr.pct("Itgb7")
Itgb4 = expr.pct("Itgb4")


df_all = rbind(Bcl2,Plxnd1,Cxcr4,S1pr1,Ccr7,Ccr9,Itgb2,Itgb7)
df_all$Count = as.factor(df_all$Count)

countFraction = 
ggplot(data = df_all, aes(x = gene, y = fraction, fill=Count)) + geom_bar(stat = "identity", position = "stack", colour="black")+ theme(legend.position = "none")

ggsave(filename = "countFraction.pdf",plot = countFraction)



  

```




```{r}
DimPlot.hashID_ko_het = 
DimPlot(so, reduction = "tsne", split.by = "group")

ggsave(filename = "DimPlot.hashID_ko_het.pdf",DimPlot.hashID_ko_het)

```
####  a large difference in the expression of Zbtb7b (ThPok) and Itgb4 (integrin B4) between the KO and HET conditions, which is very intriguing
```{r}
so_ko = subset(so, cells=which(so$group=="ko"))
so_het = subset(so, cells=which(so$group=="het"))

DimPlot.hashID_ko = 
DimPlot(so_ko, reduction = "tsne")
DimPlot.hashID_het = 
DimPlot(so_het, reduction = "tsne")

ggsave(filename = "DimPlot.hashID_ko.pdf",DimPlot.hashID_ko)
ggsave(filename = "DimPlot.hashID_het.pdf",DimPlot.hashID_het)

Idents(so) = "sample_name"
markers_ko_het_sampleName = FindMarkers(object = so, ident.1="1MF2",ident.2="1MF1", 
            logfc.threshold = 0.05, min.pct = 0.05)


Idents(so) = "group"
markers_ko_het_group = FindMarkers(object = so, ident.1="ko",ident.2="het", 
            logfc.threshold = 0.02, min.pct = 0.02)

write.csv(markers_ko_het_group, "markers_ko_het_group.csv", quote = F)

library(DT)
datatable(markers_ko_het)
so@meta.data$sample_name %>% table()
```


```{r}
DefaultAssay(so) = "RNA"
VlnPlot(so, features = c("Ccr7","Cd69","Cd4"), pt.size = 0.001)+NoLegend()
```

